import Hero from "@components/home/hero"
import Navbar from "@components/home/navbar"
import Footer from "@components/home/footer"
import Head from "next/head"


type Props = {
  children: JSX.Element
}

export default function Home({ children }: Props) {
  return (
    <>
      <Head>
        <title>Shortlink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        { children }
        <Footer />
      </main>
    </>
  )
}