import Navbar from "@components/common/navbar"
import Footer from "@components/common/footer"
import Head from "next/head"

interface IProps {
  children: JSX.Element
  login: boolean
}

export default function Home({ children, login }: IProps) : JSX.Element {
  return (
    <>
      <Head>
        <title>Shortlink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar login={login} />
        { children }
        <Footer />
      </main>
    </>
  )
}