import Head from 'next/head'
import Home from '@layouts/home'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })

export default function home() {
  return (
    <>
      <Head>
        <title>Shortlink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Home />
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident optio reiciendis veritatis, neque, facere aperiam vitae dolorem laudantium tempore minima, nisi modi quia itaque eius sed ullam eligendi. Animi ut, sit cupiditate distinctio suscipit optio quaerat quae vero tempore, odit rerum ex corporis nulla ipsa ipsum accusantium ab. Reprehenderit aliquid doloribus eum dicta nobis, ducimus laudantium ipsa molestias repellat quibusdam velit nemo adipisci quo dolores, beatae numquam itaque quidem repellendus accusantium sapiente necessitatibus. Ea quibusdam nesciunt asperiores velit. Excepturi, quis dolorum eos quam ipsum amet eaque cum commodi voluptatibus, aperiam nisi delectus non reiciendis repellat odit reprehenderit, accusamus dicta repellendus.
      </main>
    </>
  )
}
